[tool.poetry]
name = "voyageai"
version = "0.3.0rc0"
description = ""
authors = ["Yujie Qian <yujieq@voyageai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32"
aiohttp = "^3.10"
tenacity = "^9.0.0"
numpy = "^1.26"
aiolimiter = "^1.1.0"
pillow = ">=10.0.0"
pydantic = "^2.5.3"
tokenizers = "^0.20.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"