[tool.poetry]
name = "voyageai"
version = "0.3.0rc0"
description = ""
authors = ["Yujie Qian <yujieq@voyageai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"
aiohttp = "*"
tenacity = "*"
numpy = "*"
aiolimiter = "*"
pillow = "*"
pydantic = "*"
tokenizers = "*"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"